apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-integration
  labels:
    app: counter-integration
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: counter-integration
    spec:
      containers:
      - env:
        - name: PORT
          value: '8080'
        - name: MONGO
          value: mongodb://counter-integration-mongodb-svc:27017
        name: counter-integration
        image: namelosw/counter-integration:v4
        ports:
          - containerPort: 8080

      restartPolicy: Always
  selector:
    matchLabels:
      app: counter-integration

---

apiVersion: v1
kind: Service
metadata:
  name: counter-integration-svc
spec:
  selector:
    app: counter-integration
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter-integration-mongodb-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: counter-integration-mongodb
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-integration-mongodb-pvc
spec:
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-integration-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: counter-integration-mongodb
    spec:
      containers:
      - name: counter-integration-mongodb
        image: mongo
        volumeMounts:
        - mountPath: /data/db
          name: counter-integration-mongodb-data
        ports:
        - containerPort: 27017
          protocol: TCP

      volumes:
      - name: counter-integration-mongodb-data
        persistentVolumeClaim:
          claimName: counter-integration-mongodb-pvc

      restartPolicy: Always

  selector:
    matchLabels:
      app: counter-integration-mongodb

---

apiVersion: v1
kind: Service
metadata:
  name: counter-integration-mongodb-svc
spec:
  selector:
    app: counter-integration-mongodb
  ports:
  - port: 27017
    targetPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: counter-integration-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
  selector:
    app: counter-integration

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main
spec:
  backend:
    serviceName: counter-integration-nodeport
    servicePort: 80
  rules:
    - host: www.example.com
      http:
        paths:
          - backend:
              serviceName: counter-integration-nodeport
              servicePort: 80
          - path: /
            backend:
              serviceName: counter-integration-nodeport
              servicePort: 80
